### ISSUE TITLE
Can't enforce MFA to access content

### ISSUE THREAD

**Issue by avcfi** [xperseguers/mfa_frontend#3]
Currently, fe_users can opt out of using Multi-Factor Authentication (MFA), potentially leaving sensitive content unprotected. Making MFA mandatory for certain content is essential to prevent unauthorized access and uphold security standards.
I need to implement a feature that makes MFA required for specific/all content, regardless of user settings.

Have I overlooked any existing options that already enforce mandatory MFA for content?

**Comment by xperseguers** [comment]
Extension mfa_frontend is not about "protecting" content, but making sure you can use MFA (currently TOTP only) in the Frontend context.

If you want to **enforce** MFA for a given content element, you can do so thanks to another extension of mine: https://extensions.typo3.org/extension/mfa_protect

**Comment by avcfi** [comment]
Is there a way to protect and maybe hide whole pages with mfa_protect?

**Comment by avcfi** [comment]
I closed this issue as it has nothing to do with the basic mfa_frontend.
